on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Install Node.js and npm
            sudo apt-get update
            sudo apt-get install -y nodejs npm

            # Install PM2 globally
            sudo npm install pm2@latest -g

            # Navigate to project directory
            cd /var/www/html/next-level-backend

            # Pull latest changes
            git pull origin main 

            # Install project dependencies
            npm install
            
            # Restart the application using PM2
            pm2 restart all
